export const RIDE_CATEGORIES = [
  {
    id: 'go',
    name: 'Buddy Go',
    uberName: 'Uber Go',
    emoji: '🚙',
    maxPassengers: 2,
    icon: 'hatchback',
    description: 'Affordable hatchback',
    base: 25,
    perKm: 6,
  },
  {
    id: 'standard',
    name: 'Buddy Standard',
    uberName: 'UberX',
    emoji: '🚗',
    maxPassengers: 3,
    icon: 'sedan',
    description: 'Everyday rides',
    base: 35,
    perKm: 8,
    popular: true,
  },
  {
    id: 'comfort',
    name: 'Buddy Comfort',
    uberName: 'Uber Comfort',
    emoji: '✨',
    maxPassengers: 3,
    icon: 'sedan-premium',
    description: 'Newer cars, extra legroom',
    base: 50,
    perKm: 12,
  },
  {
    id: 'xl',
    name: 'Buddy XL',
    uberName: 'UberXL',
    emoji: '🚐',
    maxPassengers: 6,
    icon: 'suv',
    description: 'Group rides, extra luggage',
    base: 70,
    perKm: 15,
  },
  {
    id: 'van',
    name: 'Buddy Van',
    uberName: 'Uber Van',
    emoji: '🚌',
    maxPassengers: 7,
    icon: 'van',
    description: 'Big groups up to 7',
    base: 90,
    perKm: 18,
  },
  {
    id: 'send',
    name: 'Send',
    emoji: '📦',
    maxPassengers: 0,
    icon: 'package',
    description: 'Send parcels, documents',
    base: 40,
    perKm: 9,
    isDelivery: true,
  },
] as const;

export type RideCategory = (typeof RIDE_CATEGORIES)[number];
export type RideCategoryId = RideCategory['id'];
