ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'passenger',
  ADD COLUMN IF NOT EXISTS is_driver_approved boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS vehicle_plate text,
  ADD COLUMN IF NOT EXISTS vehicle_model text,
  ADD COLUMN IF NOT EXISTS driver_status text,
  ADD COLUMN IF NOT EXISTS is_online boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS lat double precision,
  ADD COLUMN IF NOT EXISTS lng double precision,
  ADD COLUMN IF NOT EXISTS last_update timestamptz,
  ADD COLUMN IF NOT EXISTS avg_rating numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_ratings integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rating_count_total integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rating_count jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS admin_flag boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS total_tips numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS driver_score numeric NOT NULL DEFAULT 90,
  ADD COLUMN IF NOT EXISTS acceptance_rate numeric NOT NULL DEFAULT 74,
  ADD COLUMN IF NOT EXISTS id_number_verified boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS id_number_last4 text,
  ADD COLUMN IF NOT EXISTS id_number_hash text,
  ADD COLUMN IF NOT EXISTS selfie_url text,
  ADD COLUMN IF NOT EXISTS verification_status text NOT NULL DEFAULT 'unverified',
  ADD COLUMN IF NOT EXISTS verified_at timestamptz;